### ISSUE TITLE
UAT

### ISSUE THREAD

**Issue by BK01** [bcgov/kq-ui#14]
Acceptance Criteria:

#1
As an application owner
I want to quickly fill out the KQ form without a need to create an account
So that I can get an API key for my application

#2
As an application owner
I want to access my draft metadata record (created by KQ) in BCDC
So that I can update the information and provide approval to publish

**Comment by BK01** [comment]
Feedback:
1.  Item #1: User selects an API key type (developer or production).
- The developer key text below looks good.
- Currently when user selects production, then, switches back to developer the production fields remain visible.  Change requested to have the top (API key type) section disappear once a user has made a choice.

**Comment by BK01** [comment]
Item #5: @banders 

- In the verification email received by the user add a 'click me' button in addition to the link.

**Comment by BK01** [comment]
Item #6: @banders 

- License: Remove this field from the KQ form, and set apps by default to 'Access Only'. This can be adjusted by user via BCDC UI in draft metadata if required.

**Comment by BK01** [comment]
Item #7: @banders 

- When existing metadata URL is provided, fields should populate with the existing values.

**Comment by banders** [comment]
@BK01 Regarding the request "To improve user experience provide statement to appear on mouse over for the 'app type' field.":

This can be done, but here's an alternative suggestion:  Let's just give the groups
 more descriptive titles in BCDC.  e.g. "agol" could change to "ArcGIS Online".

**Comment by banders** [comment]
@BK01 I added descriptions to all the form field labels listed in your comments above (mouse over the labels in KQ to see the descriptions).

**Comment by banders** [comment]
@BK01 I added a "Verify Request" button to the verification email.

**Comment by banders** [comment]
@BK01 license field has been removed from the form.  A default of "Access Only" has been set for new metadata records.
