### ISSUE TITLE
KQ successful submission message

### ISSUE THREAD

**Issue by BK01** [bcgov/kq-ui#18]
Once a user has completed the KQ form and clicked submit, present a message on screen indicating that the request has been received, and to wait for the email confirmation. Following this, the page can be closed.

**Comment by BK01** [comment]
Please update the existing text from:

"The API key request has been recorded. An email will be sent to you to verify the details of the request. (The email will contain a link to indicate that you have verified the request.) Once you have verified the request, it will be sent to the API owner for review and approval."

To instead be:

"The API key request has been recorded. An email will be sent to you to verify the details of the request. The email will contain a link to indicate that you have verified the request. Once you have verified the request, it will be sent to the API owner for review and approval."

**Comment by banders** [comment]
@BK01 Done.  PR is here: https://github.com/bcgov/kq-ui/pull/27
