### ISSUE TITLE
UAT - Round 2

### ISSUE THREAD

**Issue by BK01** [bcgov/kq-ui#35]
Feedback from round #2 of UAT is included below. Please implement changes to wording in user interface.

**Item i): Spelling**

Change spelling of ‘Catalog’ to instead be ‘Catalogue’
> Location in UI: "Does your application have an existing metadata record in the BC Data Catalog?"

**Item ii) Introduction Text**

Replace existing text at the top of the screen to be the following.

"Several application programming interfaces (APIs) are only accessible with an API Key.  API Keys are granted to specific applications.

There are two types of API keys: Production Keys and Developer Keys. Production Keys are to be used by applications running in a production environment and Developer Keys are to be used for non-production purposes, including application development.  It can take up to a week to process a Production Key request and receive the key, whereas a Developer Key can often be processed and received in a few minutes.

To request an API Key please complete the following form:"

**Item iii): 'API Key Type' Section**

Change title to ‘What type of API key are you requesting?’, then below have the two radio buttons and labels as they appear already. Remove all descriptive text (covered by the new intro text above).

**Comment by banders** [comment]
@BK01 I have made the changed listed above.

https://github.com/bcgov/kq-ui/pull/36
