### ISSUE TITLE
App groups in BCDC

### ISSUE THREAD

**Issue by BK01** [bcgov/kq-ui#5]
**Description:**
A question in the registration app will be -> which type of application are you registering. This 'app type' list will be generated using 'groups' in BCDC.

**Details:**
Work with the BCDC team to establish a naming standard for these groups. 

> Groups list endpoint: 

> Group name possibilities?
- AGOL
- SMK

*IMF2 places key in core, rather than site.

**Comment by BK01** [comment]
Next: Create groups (SMK, AGOL) in cad.data and add to blacklist.

**Comment by BK01** [comment]
@BK01 Add descriptions to groups in cad.data

**Comment by BK01** [comment]
@ll911 @Darv72 Initial list of group description options available for review.

**Comment by ll911** [comment]
@BK01 looks good to me, I think you can ask more feedback from the product owner of SMK and AGOL.

**Comment by BK01** [comment]
Will connect with SMK and AGOL owners today to discuss.

**Comment by BK01** [comment]
@BK01 to reword 'registry' and apply to BCDC. Group owners can adjust text in the future via the BCDC UI.

**Comment by BK01** [comment]
@ll911 New text available for group descriptions (see option 1).

**Comment by banders** [comment]
@BK01 Do you hope to display the group description in the KQ application somewhere?  If so, what do you have in mind?

**Comment by BK01** [comment]
@banders @ll911 Group descriptions in cad.data are complete. As we migrate to test and prod we can apply the same option #1 wordings to the respective groups. At this point, we only need to list the group descriptions in BCDC and not in KQ.
